
skillMetadata:
  sections:
    - name: Playing settings
      fields:
        - name: autoplay
          type: checkbox
          label: Autoplay songs after last ing playlist
          value: "True"
        - name: clean
          type: checkbox
          label: Try to play clean songs. (Not guarenteed)
          value: "True"
