
skillMetadata:
  sections:
    - name: Playing settings
      fields:
        - name: autoplay
          type: checkbox
          label: Autoplay songs after last ing playlist
          value: "True"
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
